#!/bin/sh

set -f

DAEMON=/usr/bin/uwsgi
CONF=/etc/uwsgi/*/*
LOG=/tmp/uwsgi-emperor.log

OWNER=root
GROUP=root

NAME=uwsgi
DESC=uwsgi

test -x $DAEMON || exit 0

set -e

DAEMON_OPTS="--emperor-tyrant --emperor $CONF --daemonize $LOG"

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --chuid $OWNER:$GROUP --user $OWNER \
                --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --signal 3 --user $OWNER --quiet --retry 2 --stop \
                --exec $DAEMON
        echo "$NAME."
        ;;
  reload)
        killall -1 $DAEMON
        ;;
  force-reload)
        killall -15 $DAEMON
       ;;
  restart)
        echo -n "Restarting $DESC: "
        start-stop-daemon --signal 3 --user $OWNER --quiet --retry 2 --stop \
                --exec $DAEMON
        sleep 1
        start-stop-daemon --user $OWNER --start --quiet --chuid $OWNER:$GROUP \
               --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
  status)  
        killall -10 $DAEMON
        ;;
      *)  
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
            exit 1
            ;;
    esac
    exit 0
